/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OperatorOsRouteImport } from './routes/operator-os'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorOsRoute = OperatorOsRouteImport.update({
  id: '/operator-os',
  path: '/operator-os',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/operator-os': typeof OperatorOsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/operator-os': typeof OperatorOsRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/operator-os': typeof OperatorOsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/contact'
    | '/operator-os'
    | '/privacy'
    | '/services'
    | '/solutions'
    | '/terms'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/contact'
    | '/operator-os'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/contact'
    | '/operator-os'
    | '/privacy'
    | '/services'
    | '/solutions'
    | '/terms'
    | '/services/$slug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  OperatorOsRoute: typeof OperatorOsRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-os': {
      id: '/operator-os'
      path: '/operator-os'
      fullPath: '/operator-os'
      preLoaderRoute: typeof OperatorOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  OperatorOsRoute: OperatorOsRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
